services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - '2283:3000'
    environment:
      PUBLIC_BASE_URL: https://immich.ajh657.cloud
      IMMICH_URL: http://localhost:2282
    healthcheck:
      test: curl -s http://localhost:2283/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
