services:
  dashboard:
    ports:
      - 2284:8070
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: nuclio-dashboard
    image: quay.io/nuclio/dashboard:stable-arm64
