appConfig:
  statusCheck: true
  startingView: minimal
  theme: one-dark
  customColors:
    one-dark:
      primary: '#588053'
      background: '#585858'
      background-darker: '#2B2B2B'
pageInfo:
  title: Kerdu's directory
#  auth:
#    enableOidc: true
#    oidc:
#      clientId: #TODO: add secret on local
#      endpoint: https://auth.domain.com/application/o/dashy/
sections:
  - name: Kerdu's Bookmarks
    icon: si-gitbook
    displayData:
      collapsed: false
      sortBy: default
      rows: 2
      cols: 3
    #      showForUsers: [ajh657]
    #      hideForGuests: false
    items:
      - title: Youtube
        description: ''
        icon: si-youtube
        url: https://www.youtube.com/feed/subscriptions
        target: sametab
        color: '#FF0000'
        statusCheck: false
        id: 0_937_youtube
      - title: Bluesky
        description: ''
        icon: si-bluesky
        url: https://bsky.app/
        target: sametab
        color: '#1185FE'
        statusCheck: false
        id: 1_937_bluesky
      - title: Steam
        description: ''
        icon: si-steam
        url: https://store.steampowered.com/
        target: sametab
        color: '#000000'
        statusCheck: false
        id: 2_937_steam
      - title: 'Gmail: aahoo01@gmail.com'
        description: ''
        icon: si-gmail
        url: https://mail.google.com/mail/u/0/#inbox
        target: sametab
        color: '#EA4335'
        statusCheck: false
        id: 3_937_gmail_1
      - title: 'Gmail: hoyla.arttu@gmail.com'
        description: ''
        icon: si-gmail
        url: https://mail.google.com/mail/u/1/#inbox
        target: sametab
        color: '#EA4335'
        id: 3_937_gmail_1
        statusCheck: false
      - title: 'Club Penguin Journey'
        description: ''
        icon: favicon
        url: https://play.cpjourney.net/
        target: sametab
        color: '#00529B'
        statusCheck: false
        id: 3_937_CPJ
